version: "1"

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/conf:/mosquitto/config/
  nodered:
    build:
      context: .
      dockerfile: ./nodered/dockerfile.dockerfile
    ports:
      - 1880:1880